name       : enblend-enfuse
version    : 4.2
release    : 3
source     :
    - https://nchc.dl.sourceforge.net/project/enblend/enblend-enfuse/enblend-enfuse-4.2/enblend-enfuse-4.2.tar.gz : 8703e324939ebd70d76afd350e56800f5ea2c053a040a5f5218b2a1a4300bd48
license    : GPL-2.0
component  : multimedia.graphics
summary    : Enblend and enfuse image tools
description: |
    Enblend is a tool for compositing images using a Burt&Adelson multiresolution spline. This technique tries to make the seams between the input images invisible. Enfuse is a tool for automatic exposure blending, contrast blending and much more.  It can be used to fuse an exposure bracketed step automatically into a nicely looking image.
builddeps  :
    - pkgconfig(gsl)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(OpenEXR)
    - pkgconfig(synctex)
    - help2man
    - libboost-devel
    - vigra-devel
setup      : |
    %configure --enable-openmp
build      : |
    %make
install    : |
    %make_install

